name: Dev Branch Tests

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run dummy tests
        run: |
          echo "✅ Dependencies installiert"
          echo "✅ Bot Dateien vorhanden"
          python -c "import bot; print('✅ Bot Modul importiert - OK')"
