name: Dev Branch Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dummy Test
        run: |
          echo "Dependencies installiert"
          echo "Hier könnten jetzt Unit Tests laufen (pytest, etc.)"